// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: grep/grep.proto

package grep

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Grep_CallGrep_FullMethodName = "/Grep/CallGrep"
)

// GrepClient is the client API for Grep service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GrepClient interface {
	CallGrep(ctx context.Context, in *GRPCParams, opts ...grpc.CallOption) (*GrepOutput, error)
}

type grepClient struct {
	cc grpc.ClientConnInterface
}

func NewGrepClient(cc grpc.ClientConnInterface) GrepClient {
	return &grepClient{cc}
}

func (c *grepClient) CallGrep(ctx context.Context, in *GRPCParams, opts ...grpc.CallOption) (*GrepOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrepOutput)
	err := c.cc.Invoke(ctx, Grep_CallGrep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrepServer is the server API for Grep service.
// All implementations must embed UnimplementedGrepServer
// for forward compatibility.
type GrepServer interface {
	CallGrep(context.Context, *GRPCParams) (*GrepOutput, error)
	mustEmbedUnimplementedGrepServer()
}

// UnimplementedGrepServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrepServer struct{}

func (UnimplementedGrepServer) CallGrep(context.Context, *GRPCParams) (*GrepOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallGrep not implemented")
}
func (UnimplementedGrepServer) mustEmbedUnimplementedGrepServer() {}
func (UnimplementedGrepServer) testEmbeddedByValue()              {}

// UnsafeGrepServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrepServer will
// result in compilation errors.
type UnsafeGrepServer interface {
	mustEmbedUnimplementedGrepServer()
}

func RegisterGrepServer(s grpc.ServiceRegistrar, srv GrepServer) {
	// If the following call pancis, it indicates UnimplementedGrepServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Grep_ServiceDesc, srv)
}

func _Grep_CallGrep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GRPCParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrepServer).CallGrep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Grep_CallGrep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrepServer).CallGrep(ctx, req.(*GRPCParams))
	}
	return interceptor(ctx, in, info, handler)
}

// Grep_ServiceDesc is the grpc.ServiceDesc for Grep service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Grep_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Grep",
	HandlerType: (*GrepServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallGrep",
			Handler:    _Grep_CallGrep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grep/grep.proto",
}
