// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: grep/grep.proto

package grep

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GRPCParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expr            string `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	Logfile         string `protobuf:"bytes,2,opt,name=logfile,proto3" json:"logfile,omitempty"`
	Hosts           string `protobuf:"bytes,3,opt,name=hosts,proto3" json:"hosts,omitempty"`
	Headers         bool   `protobuf:"varint,4,opt,name=headers,proto3" json:"headers,omitempty"`
	Invert          bool   `protobuf:"varint,5,opt,name=invert,proto3" json:"invert,omitempty"`
	Recursive       bool   `protobuf:"varint,6,opt,name=recursive,proto3" json:"recursive,omitempty"`
	CaseInsensitive bool   `protobuf:"varint,7,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"`
	Fixed           bool   `protobuf:"varint,8,opt,name=fixed,proto3" json:"fixed,omitempty"`
	NoShowMatch     bool   `protobuf:"varint,9,opt,name=no_show_match,json=noShowMatch,proto3" json:"no_show_match,omitempty"`
	Quiet           bool   `protobuf:"varint,10,opt,name=quiet,proto3" json:"quiet,omitempty"`
	Count           bool   `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`
	Number          bool   `protobuf:"varint,12,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *GRPCParams) Reset() {
	*x = GRPCParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grep_grep_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCParams) ProtoMessage() {}

func (x *GRPCParams) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCParams.ProtoReflect.Descriptor instead.
func (*GRPCParams) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{0}
}

func (x *GRPCParams) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

func (x *GRPCParams) GetLogfile() string {
	if x != nil {
		return x.Logfile
	}
	return ""
}

func (x *GRPCParams) GetHosts() string {
	if x != nil {
		return x.Hosts
	}
	return ""
}

func (x *GRPCParams) GetHeaders() bool {
	if x != nil {
		return x.Headers
	}
	return false
}

func (x *GRPCParams) GetInvert() bool {
	if x != nil {
		return x.Invert
	}
	return false
}

func (x *GRPCParams) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

func (x *GRPCParams) GetCaseInsensitive() bool {
	if x != nil {
		return x.CaseInsensitive
	}
	return false
}

func (x *GRPCParams) GetFixed() bool {
	if x != nil {
		return x.Fixed
	}
	return false
}

func (x *GRPCParams) GetNoShowMatch() bool {
	if x != nil {
		return x.NoShowMatch
	}
	return false
}

func (x *GRPCParams) GetQuiet() bool {
	if x != nil {
		return x.Quiet
	}
	return false
}

func (x *GRPCParams) GetCount() bool {
	if x != nil {
		return x.Count
	}
	return false
}

func (x *GRPCParams) GetNumber() bool {
	if x != nil {
		return x.Number
	}
	return false
}

type GrepOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *GrepOutput) Reset() {
	*x = GrepOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grep_grep_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrepOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrepOutput) ProtoMessage() {}

func (x *GrepOutput) ProtoReflect() protoreflect.Message {
	mi := &file_grep_grep_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrepOutput.ProtoReflect.Descriptor instead.
func (*GrepOutput) Descriptor() ([]byte, []int) {
	return file_grep_grep_proto_rawDescGZIP(), []int{1}
}

func (x *GrepOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_grep_grep_proto protoreflect.FileDescriptor

var file_grep_grep_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x72, 0x65, 0x70, 0x2f, 0x67, 0x72, 0x65, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xc9, 0x02, 0x0a, 0x0a, 0x47, 0x52, 0x50, 0x43, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x65, 0x78, 0x70, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68,
	0x6f, 0x73, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x69, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73,
	0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72,
	0x73, 0x69, 0x76, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x6e, 0x73,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f,
	0x63, 0x61, 0x73, 0x65, 0x49, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x69, 0x78, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x66, 0x69, 0x78, 0x65, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6e, 0x6f, 0x5f, 0x73, 0x68, 0x6f, 0x77,
	0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6e, 0x6f,
	0x53, 0x68, 0x6f, 0x77, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x69,
	0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x71, 0x75, 0x69, 0x65, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x24, 0x0a,
	0x0a, 0x47, 0x72, 0x65, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x32, 0x2e, 0x0a, 0x04, 0x47, 0x72, 0x65, 0x70, 0x12, 0x26, 0x0a, 0x08, 0x43,
	0x61, 0x6c, 0x6c, 0x47, 0x72, 0x65, 0x70, 0x12, 0x0b, 0x2e, 0x47, 0x52, 0x50, 0x43, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x1a, 0x0b, 0x2e, 0x47, 0x72, 0x65, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x67, 0x72, 0x65, 0x70, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grep_grep_proto_rawDescOnce sync.Once
	file_grep_grep_proto_rawDescData = file_grep_grep_proto_rawDesc
)

func file_grep_grep_proto_rawDescGZIP() []byte {
	file_grep_grep_proto_rawDescOnce.Do(func() {
		file_grep_grep_proto_rawDescData = protoimpl.X.CompressGZIP(file_grep_grep_proto_rawDescData)
	})
	return file_grep_grep_proto_rawDescData
}

var file_grep_grep_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grep_grep_proto_goTypes = []any{
	(*GRPCParams)(nil), // 0: GRPCParams
	(*GrepOutput)(nil), // 1: GrepOutput
}
var file_grep_grep_proto_depIdxs = []int32{
	0, // 0: Grep.CallGrep:input_type -> GRPCParams
	1, // 1: Grep.CallGrep:output_type -> GrepOutput
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grep_grep_proto_init() }
func file_grep_grep_proto_init() {
	if File_grep_grep_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grep_grep_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GRPCParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grep_grep_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GrepOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grep_grep_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grep_grep_proto_goTypes,
		DependencyIndexes: file_grep_grep_proto_depIdxs,
		MessageInfos:      file_grep_grep_proto_msgTypes,
	}.Build()
	File_grep_grep_proto = out.File
	file_grep_grep_proto_rawDesc = nil
	file_grep_grep_proto_goTypes = nil
	file_grep_grep_proto_depIdxs = nil
}
