// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: hydfs/repl/repl.proto

package repl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestFiles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Files []*File `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
}

func (x *RequestFiles) Reset() {
	*x = RequestFiles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hydfs_repl_repl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFiles) ProtoMessage() {}

func (x *RequestFiles) ProtoReflect() protoreflect.Message {
	mi := &file_hydfs_repl_repl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFiles.ProtoReflect.Descriptor instead.
func (*RequestFiles) Descriptor() ([]byte, []int) {
	return file_hydfs_repl_repl_proto_rawDescGZIP(), []int{0}
}

func (x *RequestFiles) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

type RequestMissing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissingFiles []*File `protobuf:"bytes,1,rep,name=missing_files,json=missingFiles,proto3" json:"missing_files,omitempty"`
}

func (x *RequestMissing) Reset() {
	*x = RequestMissing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hydfs_repl_repl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMissing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMissing) ProtoMessage() {}

func (x *RequestMissing) ProtoReflect() protoreflect.Message {
	mi := &file_hydfs_repl_repl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMissing.ProtoReflect.Descriptor instead.
func (*RequestMissing) Descriptor() ([]byte, []int) {
	return file_hydfs_repl_repl_proto_rawDescGZIP(), []int{1}
}

func (x *RequestMissing) GetMissingFiles() []*File {
	if x != nil {
		return x.MissingFiles
	}
	return nil
}

type RequestData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataFiles []*File `protobuf:"bytes,1,rep,name=data_files,json=dataFiles,proto3" json:"data_files,omitempty"`
}

func (x *RequestData) Reset() {
	*x = RequestData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hydfs_repl_repl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestData) ProtoMessage() {}

func (x *RequestData) ProtoReflect() protoreflect.Message {
	mi := &file_hydfs_repl_repl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestData.ProtoReflect.Descriptor instead.
func (*RequestData) Descriptor() ([]byte, []int) {
	return file_hydfs_repl_repl_proto_rawDescGZIP(), []int{2}
}

func (x *RequestData) GetDataFiles() []*File {
	if x != nil {
		return x.DataFiles
	}
	return nil
}

type RequestReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RequestReply) Reset() {
	*x = RequestReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hydfs_repl_repl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReply) ProtoMessage() {}

func (x *RequestReply) ProtoReflect() protoreflect.Message {
	mi := &file_hydfs_repl_repl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReply.ProtoReflect.Descriptor instead.
func (*RequestReply) Descriptor() ([]byte, []int) {
	return file_hydfs_repl_repl_proto_rawDescGZIP(), []int{3}
}

func (x *RequestReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string       `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Blocks   []*FileBlock `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hydfs_repl_repl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_hydfs_repl_repl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_hydfs_repl_repl_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *File) GetBlocks() []*FileBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type FileBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockHash int32  `protobuf:"varint,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockID   int32  `protobuf:"varint,2,opt,name=blockID,proto3" json:"blockID,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileBlock) Reset() {
	*x = FileBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hydfs_repl_repl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBlock) ProtoMessage() {}

func (x *FileBlock) ProtoReflect() protoreflect.Message {
	mi := &file_hydfs_repl_repl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBlock.ProtoReflect.Descriptor instead.
func (*FileBlock) Descriptor() ([]byte, []int) {
	return file_hydfs_repl_repl_proto_rawDescGZIP(), []int{5}
}

func (x *FileBlock) GetBlockHash() int32 {
	if x != nil {
		return x.BlockHash
	}
	return 0
}

func (x *FileBlock) GetBlockID() int32 {
	if x != nil {
		return x.BlockID
	}
	return 0
}

func (x *FileBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_hydfs_repl_repl_proto protoreflect.FileDescriptor

var file_hydfs_repl_repl_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x79, 0x64, 0x66, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x2f, 0x72, 0x65, 0x70,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x0a, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e,
	0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x0c, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x24, 0x0a, 0x0a, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x46, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x22,
	0x57, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x6b, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x41, 0x73, 0x6b, 0x12, 0x0d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x1a, 0x0f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x0d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hydfs_repl_repl_proto_rawDescOnce sync.Once
	file_hydfs_repl_repl_proto_rawDescData = file_hydfs_repl_repl_proto_rawDesc
)

func file_hydfs_repl_repl_proto_rawDescGZIP() []byte {
	file_hydfs_repl_repl_proto_rawDescOnce.Do(func() {
		file_hydfs_repl_repl_proto_rawDescData = protoimpl.X.CompressGZIP(file_hydfs_repl_repl_proto_rawDescData)
	})
	return file_hydfs_repl_repl_proto_rawDescData
}

var file_hydfs_repl_repl_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_hydfs_repl_repl_proto_goTypes = []any{
	(*RequestFiles)(nil),   // 0: RequestFiles
	(*RequestMissing)(nil), // 1: RequestMissing
	(*RequestData)(nil),    // 2: RequestData
	(*RequestReply)(nil),   // 3: RequestReply
	(*File)(nil),           // 4: File
	(*FileBlock)(nil),      // 5: FileBlock
}
var file_hydfs_repl_repl_proto_depIdxs = []int32{
	4, // 0: RequestFiles.files:type_name -> File
	4, // 1: RequestMissing.missing_files:type_name -> File
	4, // 2: RequestData.data_files:type_name -> File
	5, // 3: File.blocks:type_name -> FileBlock
	0, // 4: Replication.RequestAsk:input_type -> RequestFiles
	2, // 5: Replication.RequestSend:input_type -> RequestData
	1, // 6: Replication.RequestAsk:output_type -> RequestMissing
	3, // 7: Replication.RequestSend:output_type -> RequestReply
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hydfs_repl_repl_proto_init() }
func file_hydfs_repl_repl_proto_init() {
	if File_hydfs_repl_repl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hydfs_repl_repl_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RequestFiles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hydfs_repl_repl_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RequestMissing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hydfs_repl_repl_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RequestData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hydfs_repl_repl_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*RequestReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hydfs_repl_repl_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hydfs_repl_repl_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*FileBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hydfs_repl_repl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hydfs_repl_repl_proto_goTypes,
		DependencyIndexes: file_hydfs_repl_repl_proto_depIdxs,
		MessageInfos:      file_hydfs_repl_repl_proto_msgTypes,
	}.Build()
	File_hydfs_repl_repl_proto = out.File
	file_hydfs_repl_repl_proto_rawDesc = nil
	file_hydfs_repl_repl_proto_goTypes = nil
	file_hydfs_repl_repl_proto_depIdxs = nil
}
